NumPy Coding Tasks

1.Create Arrays

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


2.Array Operations

In [ ]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a+b)
print(a*b)

[4 6 8]
[ 3  8 15]


3.Zeros and Ones

In [ ]:
print(np.zeros((2,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4.Mean, Max, Min

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.mean())
print(arr.max())
print(arr.min())

3.0
5
1
